location ^~ /SSHlyth/ {
    proxy_pass         https://127.0.0.1:7722/;
    proxy_ssl_verify   off;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade    $http_upgrade;
    proxy_set_header   Connection "upgrade";
    proxy_set_header   Host       $host;
    proxy_set_header   X-Real-IP  $remote_addr;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_buffering    off;
    proxy_cache        off;
}
